name: iOS Build 
 
on:
  push:
    branches: [ main ]
 
jobs:
  build:
    runs-on: macos-latest 
 
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
 
    # 环境设置 
    - name: Setup Node 
      uses: actions/setup-node@v3
      with:
        node-version: '22'
 
    # 安装依赖 
    - name: Install npm packages 
      run: npm install 
      
    - name: Install CocoaPods 
      run: |
        cd ios 
        pod install 
 
    # 证书处理 
    - name: Import Certificates 
      env:
        P12_BASE64: ${{ secrets.IOS_P12_BASE64 }}
        PROVISION_BASE64: ${{ secrets.IOS_PROVISION_BASE64 }}
      run: |
        echo $P12_BASE64 | base64 --decode > cert.p12 
        echo $PROVISION_BASE64 | base64 --decode > profile.mobileprovision  
        
        # 创建钥匙串并导入证书 
        security create-keychain -p "$KEYCHAIN_PASS" build.keychain  
        security import cert.p12 -k build.keychain  -P "$P12_PASSWORD" -T /usr/bin/codesign 
        security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASS" build.keychain  
        security default-keychain -s build.keychain  
 
    # 生成jsbundle 
   # - name: Generate JS Bundle 
    #  run: npm run bundle-ios 
 
    # Xcode打包 
    - name: Build and Export IPA 
      run: |
        cd ios 
        xcodebuild archive \
          -workspace xiaoxiang.xcworkspace  \
          -scheme YourScheme \
          -archivePath build/xiaoxiang.xcarchive  
          
        xcodebuild -exportArchive \
          -archivePath build/xiaoxiang.xcarchive  \
          -exportPath build \
          -exportOptionsPlist ExportOptions.plist  
 
    # 上传产物 
    - name: Upload IPA 
      uses: actions/upload-artifact@v3
      with:
        name: app.ipa  
        path: ios/build/xiaoxiang.ipa  