name: iOS Build 
 
on:
  push:
    branches: [ main ]
 
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2' 
 
    - name: Checkout 
      uses: actions/checkout@v4
 
    # 环境设置 
    - name: Setup Node 
      uses: actions/setup-node@v4
      with:
        node-version: '22'
 
    # 安装依赖 
    - name: Install npm packages 
      run: npm install 
      
    - name: Install CocoaPods 
      run: |
        cd ios 
        pod install 
 
    # 证书处理 
    - name: Import Certificates 
      env:
        P12_BASE64: ${{ secrets.IOS_P12_BASE64 }}
        PROVISION_BASE64: ${{ secrets.IOS_PROVISION_BASE64 }}
        P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
      run: |
        echo $P12_BASE64 | base64 --decode > cert.p12 
        echo $PROVISION_BASE64 | base64 --decode > enexerProfile.mobileprovision  
        
        security create-keychain -p "$P12_PASSWORD" build.keychain
        security import cert.p12 -k build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign
        security list-keychains -s build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "$P12_PASSWORD" build.keychain
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        mv enexerProfile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
 
    # - name: Import certificates 
    #   uses: apple-actions/import-codesign-certs@v5
    #   with:
    #     keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}
    #     p12-file-base64: ${{ secrets.P12_BASE64 }}
    #     p12-password: ${{ secrets.P12_PASSWORD }}
    #     create-keychain: true 
 
    # Xcode打包 
    - name: Build IPA 
      run: |
        cd ios 
        xcodebuild archive \
          -workspace xiaoxiang.xcworkspace  \
          -scheme xiaoxiang \
          -configuration Release \
          -sdk iphonesimulator \
          -destination generic/platform=iOS \
          -archivePath build/xiaoxiang.xcarchive  

          #-sdk iphoneos18.2
             
    # 上传xcarchive 
    - name: Upload xcarchive 
      uses: actions/upload-artifact@v4
      with:
        name: xiaoxiang.xcarchive  
        path: ios/build/xiaoxiang.xcarchive  

    # - name: Unzip xcarchive
    #   run: |
    #     cd ios/xiaoxiang.xcarchive
    #     unzip xiaoxiang.xcarchive.zip
    #     pwd
    #     ls -l


    - name: Export IPA 
      run: |
        cd ios 
        xcodebuild -exportArchive \
          -archivePath build/xiaoxiang.xcarchive  \
          -exportPath build \
          -exportOptionsPlist xiaoxiang/ExportOptions.plist  
        echo '查看文件夹'
        ls -l


    # 上传IPA 
    - name: Upload IPA 
      uses: actions/upload-artifact@v4
      with:
        name: xiaoxiang.ipa  
        path: ios/build/xiaoxiang.ipa  