name: iOS Build 
 
on:
  push:
    branches: [ main ]
 
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2' 
 
    - name: Checkout 
      uses: actions/checkout@v4
 
    # 环境设置 
    - name: Setup Node 
      uses: actions/setup-node@v4
      with:
        node-version: '22'
 
    # 安装依赖 
    - name: Install npm packages 
      run: npm install 
      
    - name: Install CocoaPods 
      run: |
        cd ios 
        pod install 
 
    # 证书处理 
    - name: Import Certificates 
      env:
        P12_BASE64: ${{ secrets.IOS_P12_BASE64 }}
        PROVISION_BASE64: ${{ secrets.IOS_PROVISION_BASE64 }}
        P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
      run: |
        echo $P12_BASE64 | base64 --decode > cert.p12 
        echo $PROVISION_BASE64 | base64 --decode > profile.mobileprovision  
        
        security create-keychain -p "$P12_PASSWORD" build.keychain
        security import cert.p12 -k build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign
        security list-keychains -s build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "$P12_PASSWORD" build.keychain
 
    # 生成jsbundle 
   # - name: Generate JS Bundle 
    #  run: npm run bundle-ios 
 
    # Xcode打包 
    - name: Build and Export IPA 
      run: |
        cd ios 
        xcodebuild archive \
          -workspace xiaoxiang.xcworkspace  \
          -scheme xiaoxiang \
          -archivePath build/xiaoxiang.xcarchive  
          
        xcodebuild -exportArchive \
          -archivePath build/xiaoxiang.xcarchive  \
          -exportPath build \
          -exportOptionsPlist ExportOptions.plist  
 
    # 上传产物 
    - name: Upload IPA 
      uses: actions/upload-artifact@v4
      with:
        name: app.ipa  
        path: ios/build/xiaoxiang.ipa  