name: iOS Build 
 
on:
  push:
    branches: [ main ]
 
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2' 

    # Xcode打包 
    - name: Build IPA 
      run: |
        # cd ios 
        xcodebuild -showsdks -json
        # xcodebuild -workspace Runner.xcworkspace -scheme Runner -destination 'platform=iOS Simulator,OS=16.2,name=iPhone 14' archive -archivePath Runner.xcarchive
        # xcodebuild -exportArchive -archivePath Runner.xcarchive -exportPath Runner.ipa -exportOptionsPlist exportOptions.plist
        # xcodebuild -showsdks -json  